app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_crud:
    resource: "@AppBundle/Controller/CRUD/"
    type:     annotation

app_country:
    resource: "@AppBundle/Resources/config/routing/country.yml"
    prefix:   /country

app_university:
    resource: "@AppBundle/Resources/config/routing/university.yml"
    prefix:   /university

app_referral:
    resource: "@AppBundle/Resources/config/routing/referral.yml"
    prefix:   /referral

app_state:
    resource: "@AppBundle/Resources/config/routing/state.yml"
    prefix:   /state

app_campus:
    resource: "@AppBundle/Resources/config/routing/campus.yml"
    prefix:   /campus

app_book:
    resource: "@AppBundle/Resources/config/routing/book.yml"
    prefix:   /book

app_bookimage:
    resource: "@AppBundle/Resources/config/routing/bookimage.yml"
    prefix:   /bookimage




fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile



#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile



#hwi_oauth_redirect:
#        resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#        prefix:   /connect
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /connect
#facebook_login:
#    pattern: /login/check-facebook
#google_login:
#    pattern: /login/check-google


fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"


