
parameters:

    sujit.user_manager.class : AppBundle\Manager\UserManager
    sujit.my_mailer.class : AppBundle\Mailer\Mailer


    api_caller.options:
            timeout: 50  # maximum transport + execution duration of the call in sec.
            ssl_verifypeer: false  # to stop cURL from verifying the peer's certificate.
            useragent: "LeaseWeb API Caller"  # contents of the "User-Agent: " header.
            followlocation: true  # to follow any "Location: " header that the server sends.
            sslversion: 3  # set to 3 to avoid any bugs that relate to automatic version selection.
            fresh_connect: false  # set to true to force full reconnect every call.
    amazon_api_info:
            host : "webservices.amazon.com"
            uri : "/onca/xml"
            method: "GET"
            private_key: "RTBhZb/XIdaaPZvg4nfWAAKICREnH2vawxX+0aVU"
            aws_access_key_id: "AKIAJPTFUP4HCJFII7MQ"
            associate_tag: "stud2stud-20"
            version: "2013-08-01"
    campus_books_api_info:
            host : "http://api2.campusbooks.com"
            uri : "/12/rest/bookprices"
            api_key: "s2SmHJAVMOykHAOdaG55"
    campus_books_api_info_lowest_price:
            host : "http://api2.campusbooks.com"
            uri : "/12/rest/prices"
            api_key: "s2SmHJAVMOykHAOdaG55"
    google_re_captcha_info:
            host: "https://www.google.com/recaptcha/api/siteverify"
            secret: "6LfXfBwTAAAAAJeXK5uHanz7UJWCXIN8_qvBzmjq"


services:


    sujit.my_mailer :
        class: "%sujit.my_mailer.class%"
        arguments: ["@mailer", "@router","@templating",{"confirmation.template":"%fos_user.registration.confirmation.template%","resetting.template":"%fos_user.resetting.email.template%","from_email":{"confirmation":"%fos_user.registration.confirmation.from_email%","resetting":"%fos_user.resetting.email.from_email%"}}]


    sujit.user_manager :
        class: "%sujit.user_manager.class%"
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer","@fos_user.util.email_canonicalizer","@fos_user.entity_manager", "%fos_user.model.user.class%"]


    app.form.registration:
            class: AppBundle\Form\Type\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }
    app.form.handler.registration:
            class: AppBundle\Form\Handler\RegistrationFormHandler
            arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
            scope: request
            public: false
    app.form.resetting:
            class: AppBundle\Form\Type\ResettingType
            tags:
                - { name: form.type, alias: app_password_resetting }

    app.form.handler.resetting:
                class: AppBundle\Form\Handler\ResettingFormHandler
                arguments: ["@fos_user.resetting.form", "@request", "@fos_user.user_manager"]
                scope: request
                public: false

    app.form.change_password:
                class: AppBundle\Form\Type\ChangePasswordType
                tags:
                    - { name: form.type, alias: app_password_changing }

    app.form.handler.change_password:
                class: AppBundle\Form\Handler\ChangePasswordFormHandler
                arguments: ["@fos_user.change_password.form", "@request", "@fos_user.user_manager"]
                scope: request
                public: false


    app.validator.username_exist:
            class: AppBundle\Validator\UsernameValidator
            arguments: ["@doctrine.orm.entity_manager"]

            tags:
                - { name: validator.constraint_validator, alias: app.validator.username_exist }


    app.user.repository:
            class: Doctrine\ORM\EntityRepository
            factory: [@doctrine.orm.entity_manager, getRepository]
            arguments:
                - AppBundle\Entity\User



    app.oauth.social_plugin_grant_extension:
            class: AppBundle\OAuth\SocialPluginGrantExtension
            arguments: ["@app.user.repository"]
            tags:
                - { name: fos_oauth_server.grant_extension, uri: 'http://platform.local/grants/social_plugin' }


