

# WEB CONTROLLER ROUTES


#Security Controller
home:
    path:      /
    defaults:  { _controller: AppBundle:Security:index }

login:
    path:      /login
    defaults:  { _controller: AppBundle:Security:login }

user_homepage:
    path:      /user/dashboard
    defaults:  { _controller: AppBundle:Security:userDashboard }

#Reasetting Controller
reset_password:
    path: /resetting/reset/{token}
    defaults: {_controller: AppBundle:Resetting:reset}
    methods: [POST,GET]

resetting_password_send_email:
    path: /resetting/send-email
    defaults: {_controller: AppBundle:Resetting:sendEmail}
    methods: [POST]

#Registration Controller
check_if_username_exist:
    path: /check_if_username_exist
    defaults:  {_controller: AppBundle:Registration:checkIfUsernameExist}
    methods: [POST]

check_if_email_exist:
    path: /check_if_email_exist
    defaults:  {_controller: AppBundle:Registration:checkIfEmailExist}
    methods: [POST]

user_registration:
    path: /register
    defaults:  {_controller: AppBundle:Registration:register}

fos_user_registration_check_email:
    path: /check-email
    defaults: {_controller: AppBundle:Registration:checkEmail}

user_registration_confirm:
    path: /confirm/{token}
    defaults: {_controller: AppBundle:Registration:confirm}
    methods: [GET]

fos_user_registration_confirmed:
    path: /confirmed
    defaults: {_controller: AppBundle:Registration:confirmed}

confirmation_token_expired:
    path: /confirmation_token_expired
    defaults: {_controller: AppBundle:Registration:confirmationTokenExpired}

#SocialRegistrationController

social_user_registration:
    path: /social_register
    defaults: {_controller: AppBundle:SocialRegistration:socialRegister}
    methods: [POST,GET]

auth_google:
    path: /auth/google
    defaults: {_controller: AppBundle:SocialRegistration:authGoogle}
    methods: [POST]

auth_facebook:
    path: /auth/facebook
    defaults: {_controller: AppBundle:SocialRegistration:authFacebook}
    methods: [POST]

update_social_user:
    path: /update_social_user
    defaults: {_controller: AppBundle:SocialRegistration:updateSocialUser}
    methods: [POST]

#ChangePasswordController
change_password:
    path: /profile/change-password
    defaults: {_controller: AppBundle:ChangePassword:changePassword}
    methods: [POST,GET]







# API CONTROLLER ROUTES




#UserApiController
#update_created_profile:
#    path: /api/user/update_created_profile
#    defaults: {_controller: AppBundle:Api/UserApi:updateCreatedProfile}
#    methods: [POST]

#update_profile:
#    path: /user/update_profile
#    defaults:  {_controller: AppBundle:Api/UserApi:updateUser}
#    methods: [GET,POST]

current_user_short_details:
    path: /api/current_user_short_details
    defaults:  {_controller: AppBundle:Api/UserApi:currentUserShortDetails}

current_user_full_details:
    path: /api/current_user_full_details
    defaults:  {_controller: AppBundle:Api/UserApi:currentUserFullDetails}

admin_all_users:
    path: /api/admin/all_users
    defaults:  {_controller: AppBundle:Api/UserApi:adminAllUsers}



#user_update_full_name:
#    path: /api/update_user_full_name
#    defaults:  {_controller: AppBundle:Api/UserApi:updateUserFullNameData}
#    methods: [POST]
#
#user_update_university_campus:
#    path: /api/update_user_university_campus
#    defaults:  {_controller: AppBundle:Api/UserApi:updateUserUniversityCampus}
#    methods: [POST]

update_user_profile:
    path: /api/update_user_profile
    defaults:  {_controller: AppBundle:Api/UserApi:updateUserProfile}
    methods: [POST]


#BookManagementApiController

books_search_by_keyword_amazon:
    path: /book/search_by_keyword_amazon
    defaults:  {_controller: AppBundle:Api/BookManagementApi:searchByKeywordAmazonApi}
    methods: [POST]

books_search_by_keyword_amazon_api:
    path: /api/book/search_by_keyword_amazon_api
    defaults:  {_controller: AppBundle:Api/BookManagementApi:searchByKeywordAmazonApiWithApiCall}
    methods: [POST]

books_search_by_asin_amazon:
    path: /book/search_by_asin_amazon
    defaults:  {_controller: AppBundle:Api/BookManagementApi:searchByAsinAmazonApi}
    methods: [POST]

books_search_by_isbn_amazon:
    path: /book/search_by_isbn_amazon
    defaults:  {_controller: AppBundle:Api/BookManagementApi:searchByIsbnAmazonApi}
    methods: [POST]

books_search_by_isbn_campus_books:
    path: /book/search_by_isbn_campus_books
    defaults:  {_controller: AppBundle:Api/BookManagementApi:searchByIsbnCampusBooksApi}
    methods: [POST]

get_lowest_online_price_campus_books_by_isbn:
    path: /book/get_lowest_price_by_isbn_campus_books
    defaults:  {_controller: AppBundle:Api/BookManagementApi:getLowestPriceByIsbnCampusBooksApi}
    methods: [GET]

get_amazon_cart_create_url:
    path: /book/get_amazon_cart_create_url
    defaults:  {_controller: AppBundle:Api/BookManagementApi:getAmazonCartCreateUrl}
    methods: [POST]

get_campus_deals_by_isbn_api:
    path: /api/book/get_campus_deals_by_isbn_api
    defaults:  {_controller: AppBundle:Api/BookManagementApi:getCampusDealsByIsbnApi}
    methods: [POST]

get_campus_deals_by_isbn:
    path: /book/get_campus_deals_by_isbn
    defaults:  {_controller: AppBundle:Api/BookManagementApi:getCampusDealsByIsbn}
    methods: [POST]

#get_on_campus_deals_by_isbn:
#    path: /api/book/get_on_campus_deals_by_isbn
#    defaults:  {_controller: AppBundle:Api/BookManagementApi:getOnCampusDealsByIsbn}
#    methods: [POST]


add_new_sell_book:
    path: /api/book/add_new_sell_book
    defaults:  {_controller: AppBundle:Api/BookManagementApi:addNewSellBook}
    methods: [POST]

add_new_custom_sell_book:
    path: /api/book/add_new_custom_sell_book
    defaults:  {_controller: AppBundle:Api/BookManagementApi:addNewCustomSellBook}
    methods: [POST]


#CampusManagementApiController

campus_list_by_university:
    path: /api/campus/list
    defaults:  {_controller: AppBundle:Api/CampusManagementApi:campusListByUniversity}
    methods: [POST]

campus_details_with_university_and_state:
    path: /campus/details_with_university_and_state
    defaults:  {_controller: AppBundle:Api/CampusManagementApi:campusDetailsWithUniversityAndState}
    methods: [POST]

update_campus:
    path: /api/campus/update
    defaults:  {_controller: AppBundle:Api/CampusManagementApi:updateCampus}
    methods: [POST]

save_new_campus:
    path: /api/campus/add
    defaults:  {_controller: AppBundle:Api/CampusManagementApi:saveNewCampus}
    methods: [POST]

delete_university:
    path: /api/university/delete
    defaults:  {_controller: AppBundle:Api/CampusManagementApi:deleteUniversity}
    methods: [POST]


#CountryManagementApiController

all_countries:
    path: /country/list
    defaults:  {_controller: AppBundle:Api/CountryManagementApi:countryList}

all_countries_api:
    path: /api/country/list
    defaults:  {_controller: AppBundle:Api/CountryManagementApi:countryListAdmin}

#ReferralManagementApiController

all_referrals_api:
    path: /api/referral/list
    defaults:  {_controller: AppBundle:Api/ReferralManagementApi:referralListAdmin}

all_referrals:
    path: /referral/list
    defaults:  {_controller: AppBundle:Api/ReferralManagementApi:referralList}


#StateManagementApiController

all_states_by_country:
    path: /state/list_by_country
    defaults:  {_controller: AppBundle:Api/StateManagementApi:statesByCountry}
    methods: [POST]

all_states_by_country_api:
    path: /api/state/list_by_country
    defaults:  {_controller: AppBundle:Api/StateManagementApi:statesByCountryAdmin}
    methods: [POST]

#UniversityManagementApiController

university_list:
    path: /university/autocomplete_activated_search_list
    defaults:  {_controller: AppBundle:Api/UniversityManagementApi:universityAutocompleteActivatedSearchList}
    methods: [POST]

university_name_list:
    path: /api/university/autocomplete_university_name_search_list
    defaults:  {_controller: AppBundle:Api/UniversityManagementApi:universityAutocompleteNameSearchList}
    methods: [POST]

university_search:
    path: /api/university/search
    defaults:  {_controller: AppBundle:Api/UniversityManagementApi:universitySearchAdmin}
    methods: [POST]

update_university:
    path: /api/university/update_university
    defaults:  {_controller: AppBundle:Api/UniversityManagementApi:updateUniversity}
    methods: [POST]

save_new_university:
    path: /university/save_new_university
    defaults:  {_controller: AppBundle:Api/UniversityManagementApi:saveNewUniversity}
    methods: [POST]


save_new_university_admin:
    path: /api/university/save_new_university
    defaults:  {_controller: AppBundle:Api/UniversityManagementApi:saveNewUniversityAdmin}
    methods: [POST]

delete_university:
    path: /api/university/delete
    defaults:  {_controller: AppBundle:Api/UniversityManagementApi:deleteUniversity}
    methods: [POST]

#ContactManagementApiController

add_contact_api:
    path: /api/contact/add_contact_api
    defaults:  {_controller: AppBundle:Api/ContactManagementApi:addNewContactApi}
    methods: [POST]

add_contact:
    path: /contact/add_contact
    defaults:  {_controller: AppBundle:Api/ContactManagementApi:addNewContact}
    methods: [POST]

get_messages:
    path: /api/contact/get_messages
    defaults:  {_controller: AppBundle:Api/ContactManagementApi:getMessages}
    methods: [POST]

send_messages:
    path: /api/contact/send_messages
    defaults:  {_controller: AppBundle:Api/ContactManagementApi:sendMessages}
    methods: [POST]


#BookDealManagementApiController

get_book_deals_i_have_contacted_for:
    path: /api/book_deal/get_book_deals_i_have_contacted_for
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:getBooksIHaveContactedFor}
    methods: [POST]

get_book_deals_i_have_created:
    path: /api/book_deal/get_book_deals_i_have_created
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:getBooksIHaveCreated}
    methods: [POST]

sell_book_to_user:
    path: /api/book_deal/sell_book_to_user
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:sellBookToUser}
    methods: [POST]

get_book_deals_i_have_created_and_sold:
    path: /api/book_deal/get_book_deals_i_have_created_and_sold
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:getBooksIHaveCreatedAndSold}
    methods: [POST]

get_book_deals_i_have_bought:
    path: /api/book_deal/get_book_deals_i_have_bought
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:getBooksIHaveBought}
    methods: [POST]

change_book_deal_status:
    path: /api/book_deal/change_book_deal_status
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:changeBookDealStatus}
    methods: [POST]

get_lowest_campus_deal_price:
    path: /api/book_deal/get_lowest_campus_deal_price
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:getLowestCampusDealPrice}
    methods: [POST]

update_book_deal:
    path: /api/book_deal/update_book_deal
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:updateBookDeal}
    methods: [POST]

delete_book_deal:
    path: /api/book_deal/delete_book_deal
    defaults:  {_controller: AppBundle:Api/BookDealManagementApi:deleteBookDeal}
    methods: [POST]


#WishList Management Api Controller

add_book_to_wish_list:
    path: /api/wishlist/add_book_to_wish_list
    defaults:  {_controller: AppBundle:Api/WishListManagementApi:addBookToWishList}
    methods: [POST]

get_my_wishlist:
    path: /api/wishlist/get_my_wishlist
    defaults:  {_controller: AppBundle:Api/WishListManagementApi:getMyWishList}
    methods: [GET]

remove_wishlist_item:
    path: /api/wishlist/remove_wishlist_item
    defaults:  {_controller: AppBundle:Api/WishListManagementApi:removeWishListItem}
    methods: [POST]


#Admin User Api Controller

get_all_non_approved_user:
    path: /api/admin/get_all_non_approved_user
    defaults:  {_controller: AppBundle:Api/AdminUserApi:getAllNonApprovedUser}
    methods: [POST]

get_all_approved_user:
    path: /api/admin/get_all_approved_user
    defaults:  {_controller: AppBundle:Api/AdminUserApi:getAllApprovedUser}
    methods: [POST]

get_all_admin_user:
    path: /api/admin/get_all_admin_user
    defaults:  {_controller: AppBundle:Api/AdminUserApi:getAllAdminUser}
    methods: [POST]

admin_update_users:
    path: /api/admin/update_user_data
    defaults:  {_controller: AppBundle:Api/AdminUserApi:adminUpdateUserData}
    methods: [POST]

approve_users:
    path: /api/admin/approve_users
    defaults:  {_controller: AppBundle:Api/AdminUserApi:approveUsers}
    methods: [POST]

add_admin_user:
    path: /api/admin/add_admin_user
    defaults:  {_controller: AppBundle:Api/AdminUserApi:addAdminUser}
    methods: [POST]

#Admin BookDeal Api Controller

get_all_book_deals:
    path: /api/admin/get_all_book_deals
    defaults:  {_controller: AppBundle:Api/AdminBookDealApi:getAllBookDeals}
    methods: [POST]

#QuoteManagementApiController

get_student_quotes:
    path: /api/admin/get_student_quotes
    defaults:  {_controller: AppBundle:Api/AdminQuoteApi:getStudentQuotes}
    methods: [POST]

get_university_quotes:
    path: /api/admin/get_university_quotes
    defaults:  {_controller: AppBundle:Api/AdminQuoteApi:getUniversityQuotes}
    methods: [POST]

update_quote:
    path: /api/admin/update_quote
    defaults:  {_controller: AppBundle:Api/AdminQuoteApi:updateQuote}
    methods: [POST]

add_quote:
    path: /api/admin/add_quote
    defaults:  {_controller: AppBundle:Api/AdminQuoteApi:addQuote}
    methods: [POST]


#AdminNewsManagementApiController

get_news:
    path: /api/admin/get_news
    defaults:  {_controller: AppBundle:Api/AdminNewsApi:getNews}
    methods: [POST]

add_news:
    path: /api/admin/add_news
    defaults:  {_controller: AppBundle:Api/AdminNewsApi:addNews}
    methods: [POST]

update_news:
    path: /api/admin/update_news
    defaults:  {_controller: AppBundle:Api/AdminNewsApi:updateNews}
    methods: [POST]

#NewsManagementApiController

get_active_news:
    path: /news/get_activated_news
    defaults:  {_controller: AppBundle:Api/NewsApi:getActiveNews}
    methods: [POST]

get_single_news:
    path: /news/get_single_news
    defaults:  {_controller: AppBundle:Api/NewsApi:getSingleNews}
    methods: [POST]


#ContactUsController
send_message:
    path: /contactus/send_message
    defaults:  {_controller: AppBundle:Api/ContactUsApi:sendMessage}
    methods: [POST]
