app_quote:
    resource: "@AppBundle/Resources/config/routing/quote.yml"
    prefix:   /quote

app_message:
    resource: "@AppBundle/Resources/config/routing/message.yml"
    prefix:   /message

app_contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

app_wishlist:
    resource: "@AppBundle/Resources/config/routing/wishlist.yml"
    prefix:   /wishlist

app_bookdeal:
    resource: "@AppBundle/Resources/config/routing/bookdeal.yml"
    prefix:   /bookdeal

app_book:
    resource: "@AppBundle/Resources/config/routing/book.yml"
    prefix:   /book

app_bookimage:
    resource: "@AppBundle/Resources/config/routing/bookimage.yml"
    prefix:   /bookimage

app_campus:
    resource: "@AppBundle/Resources/config/routing/campus.yml"
    prefix:   /campus

app_state:
    resource: "@AppBundle/Resources/config/routing/state.yml"
    prefix:   /state

app_country:
    resource: "@AppBundle/Resources/config/routing/country.yml"
    prefix:   /country

app_university:
    resource: "@AppBundle/Resources/config/routing/university.yml"
    prefix:   /university

app_referral:
    resource: "@AppBundle/Resources/config/routing/referral.yml"
    prefix:   /referral

