AppBundle\Entity\BookImage:
    type: entity
    table: 	book_images
    repositoryClass: AppBundle\Repository\BookImageRepository



    manyToOne:
        book:
            targetEntity: Book
            inversedBy: bookImages
            joinColumn:
              name: book_id
              referencedColumnName: id


    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        imageName:
            column: image_name
            nullable: true
            type: string
            length: '255'
        imageUrl:
            column: image_url
            nullable: true
            type: string
            length: '255'
        titleImage:
            column: title_image
            nullable: true
            type: boolean



    lifecycleCallbacks: {  }
